<?php

echo "<h1 style='text-align:center;'>Product List</h1>";

echo PHP_EOL;

echo $this->tag->linkTo([
    'product',
    'Add Product! '
]);
echo $this->tag->linkTo([
    'order',
    'Add Order! '
]);
if ($products->count() > 0 ) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>Product ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Tags</th>
            <th>Price</th>
            <th>Stock</th>
            <th>Action</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Total Products: <?php echo $products->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($products as $product) 
        {
?>
            
            
            <tr>
                <td><?php echo $product->productid; ?></td>
                <td><?php echo $product->name; ?></td>
                <td><?php echo $product->description; ?></td>
                <td><?php echo $product->tags; ?></td>
                <td><?php echo $product->price; ?></td>
                <td><?php echo $product->stock; ?></td>
                <td><?php //echo $this->tag->linkTo([
                        //'edit/edit/'.$user->id,
                        //'Edit', 'class' => 'btn btn-primary' ]);?>
                    <?php echo $this->tag->linkTo([
                            'index/delete/'.$product->productid,
                            'Delete', 'class' => 'btn btn-danger' ]);?></td>

            </tr>
        <?php

}   }  
echo $this->tag->linkTo([
    'index2',
    'Show Order!  '
]); 
echo $this->tag->linkTo([
    'settings',
    'Settings!  '
]);    ?>
        </tbody>
    </table>
    
